alter table campus_times
  add column if not exists neighborhood text not null default '',
  add column if not exists dining text not null default '',
  add column if not exists male_dorms text not null default '',
  add column if not exists female_dorms text not null default '',
  add column if not exists male_sg_zones text not null default '',
  add column if not exists female_sg_zones text not null default '';

update campus_times set neighborhood='North Neighborhood', dining='McNutt Dining Hall', male_dorms='McNutt South South, McNutt South East, McNutt South West', female_dorms='McNutt North North, McNutt North East, McNutt North West', male_sg_zones=E'• McNutt South Dorms\n• McNutt South Courtyard\n• McNutt East Lawn', female_sg_zones=E'• McNutt North Dorms\n• McNutt North Courtyard\n• McNutt North and East Lawns' where campus_name='Blankenbaker';
update campus_times set neighborhood='South Neighborhood', dining='Wright Dining Hall', male_dorms='Eigenmann', female_dorms='Eigenmann', male_sg_zones=E'• Eigenmann Dorm\n• Teter South East Lawn (South of Thompson)', female_sg_zones=E'• Eigenmann Dorm\n• Teter South West Lawn (South of Wissler)' where campus_name='Bullitt County';
update campus_times set neighborhood='South Neighborhood', dining='Wright Dining Hall', male_dorms='Teter-Thompson', female_dorms='Teter-Boisen', male_sg_zones=E'• Thompson Dorm\n• Thompson West Lawn\n• Thompson East Strip', female_sg_zones=E'• Boisen Dorm\n• Boisen East Strip' where campus_name='Crestwood';
update campus_times set neighborhood='South Neighborhood', dining='Wright Dining Hall', male_dorms='Eigenmann', female_dorms='Eigenmann', male_sg_zones=E'• Eigenmann Dorm\n• Teter Lawn - West of Elkin', female_sg_zones=E'• Eigenmann Dorm\n• Teter Lawn West of Boisen (between Elkin and Boisen)' where campus_name='Elizabethtown';
update campus_times set neighborhood='South Neighborhood', dining='McNutt Dining Hall', male_dorms='Foster-Shea', female_dorms='Walnut Grove-Chestnut', male_sg_zones=E'• Shea Dorm\n• Shea East Lawn (South portion)', female_sg_zones=E'• Chestnut D Dorm\n• Chestnut East Lawn (South portion)' where campus_name='Franklin';
update campus_times set neighborhood='South Neighborhood', dining='McNutt Dining Hall', male_dorms='Foster-Shea', female_dorms='Foster-Harper', male_sg_zones=E'• Shea Dorm\n• Shea West Lawn', female_sg_zones=E'• Harper Dorm\n• Harper East Lawn (North portion)' where campus_name='Indiana';
update campus_times set neighborhood='South Neighborhood', dining='TBD', male_dorms='Teter-Thompson', female_dorms='Teter-Wissler', male_sg_zones=E'• Thompson Dorm\n• Thompson West Lawn\n• Thompson East Strip', female_sg_zones=E'• Wissler Dorm\n• Wissler West Lawn' where campus_name='La Grange';
update campus_times set neighborhood='North Neighborhood', dining='TBD', male_dorms='Foster-Jenkinson', female_dorms='Foster-Harper', male_sg_zones=E'• Jenkinson Dorm\n• Jenkinson East Lawn', female_sg_zones=E'• Harper Dorm\n• Jenkinson East Lawn' where campus_name='Nelson County';
update campus_times set neighborhood='North Neighborhood', dining='McNutt Dining Hall', male_dorms='Foster-Shea', female_dorms='Foster-Harper', male_sg_zones=E'• Shea Dorm\n• Shea East Lawn (North portion)', female_sg_zones=E'• Harper Dorm\n• Harper East Lawn (South portion)' where campus_name='Prospect';
update campus_times set neighborhood='North Neighborhood', dining='McNutt Dining Hall', male_dorms='Foster-Martin', female_dorms='Foster-Magee', male_sg_zones=E'• Martin Dorm\n• Martin East Lawn (North portion)', female_sg_zones=E'• Magee Dorm\n• Magee East Lawn (North portion)' where campus_name='Shelby County';
update campus_times set neighborhood='North Neighborhood', dining='McNutt Dining Hall', male_dorms='Foster-Martin', female_dorms='Foster-Magee', male_sg_zones=E'• Martin Dorm\n• Martin East Lawn (South portion)', female_sg_zones=E'• Magee Dorm\n• Magee East Lawn (South portion)' where campus_name='South Lou / Beechmont';
update campus_times set neighborhood='North Neighborhood', dining='McNutt Dining Hall', male_dorms='McNutt South West', female_dorms='Walnut Grove-Chestnut D', male_sg_zones=E'• McNutt South West Dorm\n• McNutt South Lawn', female_sg_zones=E'• Chestnut D Dorm\n• Chestnut East Lawn (North portion)' where campus_name='Southwest';
